apiVersion: v1
kind: Service
metadata:
  name: sai-trading-bot-service
spec:
  selector:
    app: sai-trading-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
