apiVersion: v1
kind: Secret
metadata:
  name: sai-bot-secrets
type: Opaque
stringData:
  API_KEY: "yvXhKnIEIn5wRmGtWOlRziIWpVXZ73P1zgPWkT5KYBmWjRQfkyaa4Gzufx9pf1xT"
  SECRET_KEY: "PZXFx5NFQDPVt7PtSm5YBIZv9IHNSrkx91BuVqsZxfDPuW0GfFKr8FCHkcw7SSsO"
